### ISSUE TITLE
Escape key unusable outside thomas

### ISSUE THREAD

**Issue by Petemir** [andrepolischuk/thomas#11]
When thomas is open, I can't use the escape key for anything else... it's kind of intrusive/blocker (considering that shortcuts aren't customized by the user).

Using Ubuntu 18.04, thomas v1.7.9.

**Comment by andrepolischuk** [comment]
sorry for waiting. you can customize shortcuts in config file (~/.thomas.json) or on settings page (top-right astericks icon in the latest app version).

**Comment by Petemir** [comment]
Hello, don't worry about the delay.

I see no settings page nor asterisk icon, but the config file just works. Thanks.

**Comment by andrepolischuk** [comment]
Latest version has a built-in settings page

https://github.com/andrepolischuk/thomas/releases/tag/v0.4.1
