### ISSUE TITLE
There is no package-lock.json file

### ISSUE THREAD

**Issue by yashghelani** [andrepolischuk/thomas#6]
Everytime I update the repo using `npm update`, npm always created a package-lock.json file. This file is supposed to be committed according to [this](https://docs.npmjs.com/files/package-lock.json).

Please commit that and I'll fetch it.

Thanks for your awesome app 😁

**Comment by andrepolischuk** [comment]
Oh, I still use npm 4 =) But it’s good idea, thanks.

**Comment by andrepolischuk** [comment]
I’m going add it this day. Or you can send me pr.

**Comment by andrepolischuk** [comment]
Added
